### ISSUE TITLE
Border edge consistency

### ISSUE THREAD

**Issue by SaucySauce** [hrdwrrsk/AdwaitaExtended#6]
The borders of the applications dash, workspaces dash, the dock's windows counters, could have the same border edge radius.

**Comment by SaucySauce** [comment]
![Screenshot-20200418193146-1280x800](https://user-images.githubusercontent.com/38703177/79669477-4aa5ec00-81ab-11ea-9ebc-2990dca579c3.png)

**Comment by hrdwrrsk** [comment]
It's already same, seems like you are enabling dash-to-dock's "Shirink mode"

**Comment by SaucySauce** [comment]
Oh yeah, my bad, I just enabled normal size and it's great. Sorry for the inconvenience.
